batch_size: 31  # 需要同步在BgsubDataset里面修改batch_size
iters: 1000000

train_dataset:
  type: BgsubDataset
  dataset_root: data/bgsData
  train_file: train
  transforms:
    - type: LoadImages
    - type: RandomDistort
    - type: RandomBlur
      prob: 0.1
    - type: RandomSharpen
      prob: 0.2
    - type: RandomNoise
      prob: 0.5
    - type: RandomReJpeg
      prob: 0.2
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: BgsubDataset
  dataset_root: data/bgsData
  val_file: val
  transforms:
    - type: LoadImages
    - type: Normalize
    - type: ResizeToPixels
  mode: val
  get_trimap: False

model:
  type: PPMattingV2
  backbone:
    type: STDC1
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
  decoder_channels: [128, 96, 64, 32, 16]
  head_channel: 8
  dpp_output_channel: 256
  dpp_merge_type: add
  

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 5.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9
  warmup_iters: 1000
  warmup_start_lr: 1.0e-5

