_base_: modnet_mobilenetv2.yml
batch_size: 36
iters: 300000
model:
  backbone:
    type: MobileNetV3_small_x1_0
    pretrained: Null
    # pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz

