_base_: modnet_mobilenetv2.yml
batch_size: 36
iters: 300000
model:
  backbone:
    type: MobileNetV3_large_x1_0
    pretrained: https://paddledet.bj.bcebos.com/models/pretrained/MobileNetV3_large_x1_pretrained.pdparams

