_base_: '../_base_/BingImages30787_480.yml'
batch_size: 10
iters: 1600000

model:
  type: SegFormer_B2
  num_classes: 1
  pretrained: https://bj.bcebos.com/paddleseg/dygraph/mix_vision_transformer_b2.tar.gz
